use risc_v_compiler::ast::Program;
use risc_v_compiler::code_gen::{CGError, CodeGen};
use risc_v_compiler::parser::{ParseError, Parser};
use risc_v_compiler::scanner::{ScanError, Scanner};
use risc_v_compiler::token::SyntaxToken;
use std::path::Path;

#[derive(Debug)]
enum CompileError {
    Scan(ScanError),
    Parse(ParseError),
    CodeGen(CGError),
}

impl std::fmt::Display for CompileError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            CompileError::Scan(e) => write!(f, "Compile Error: {e}"),
            CompileError::Parse(e) => write!(f, "Compile Error: {e}"),
            CompileError::CodeGen(e) => write!(f, "Compile Error: {e}"),
        }
    }
}

impl std::error::Error for CompileError {}

impl From<ScanError> for CompileError {
    fn from(e: ScanError) -> Self {
        CompileError::Scan(e)
    }
}

impl From<ParseError> for CompileError {
    fn from(e: ParseError) -> Self {
        CompileError::Parse(e)
    }
}

impl From<CGError> for CompileError {
    fn from(e: CGError) -> Self {
        CompileError::CodeGen(e)
    }
}

fn scan(src: &str) -> Result<Vec<SyntaxToken>, ScanError> {
    Scanner::new(src).scan()
}

fn parse(sts: &Vec<SyntaxToken>) -> Result<Program, ParseError> {
    Parser::new(sts).parse()
}

fn generate(ast: &Program) -> Result<String, CGError> {
    CodeGen::new(ast).generate()
}

fn compile(src: &str, src_path: &Path) -> Result<String, CompileError> {
    let header = format!(
        "# Generated by a toy compiler from {}\n# Target: RISC-V (RV32I)\n\n",
        src_path.display()
    );
    let sts = scan(src)?;
    let ast = parse(&sts)?;
    let code = generate(&ast)?;

    Ok(header + &code)
}

fn main() -> () {
    // 1. Parse command line argument
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 2 {
        eprintln!("Usage: {} <file>", args[0]);
        std::process::exit(1);
    }

    // 2. Read input file into src
    let src_path = Path::new(&args[1]);
    let src = std::fs::read_to_string(src_path).unwrap_or_else(|e| {
        eprintln!("Error reading '{}':{e}", src_path.display());
        std::process::exit(1);
    });

    // 3. Compile src to output
    let output = match compile(&src, src_path) {
        Ok(code) => code,
        Err(e) => {
            eprintln!("\n{e}\n");
            std::process::exit(1);
        }
    };

    // 4. Write output to a file
    let output_path = src_path.with_extension("s");
    std::fs::write(&output_path, output).unwrap_or_else({
        |e| {
            eprintln!("Error writing '{}':{e}", output_path.display());
            std::process::exit(1);
        }
    });

    println!("{} -> {}", src_path.display(), output_path.display());
}
